In [2]:
import numpy as np


In [4]:
a = [x for x in range(10, 16)]
import numpy as np
n_a = np.array(a)
n_a

n_a[0]
n_a[1]
last_index = len(n_a) - 1
n_a[last_index]
n_a[-1] 
n_a[-2]

n_a[2:]

array([12, 13, 14, 15])

In [5]:

n_a[::2]

array([10, 12, 14])

In [6]:
n_b = np.array([x for x in range(100, 106)])

In [8]:
n_c = np.concatenate([n_a, n_b])

In [9]:
n_c

array([ 10,  11,  12,  13,  14,  15, 100, 101, 102, 103, 104, 105])