In [2]:
import numpy as np


In [4]:
a = [x for x in range(10, 16)]
import numpy as np
n_a = np.array(a)
n_a

n_a[0]
n_a[1]
last_index = len(n_a) - 1
n_a[last_index]
n_a[-1] 
n_a[-2]

n_a[2:]

array([12, 13, 14, 15])

In [5]:

n_a[::2]

array([10, 12, 14])

In [6]:
n_b = np.array([x for x in range(100, 106)])

In [8]:
n_c = np.concatenate([n_a, n_b])

In [9]:
n_c

array([ 10,  11,  12,  13,  14,  15, 100, 101, 102, 103, 104, 105])

In [2]:

a = [x for x in range(10, 16)]
import numpy as np
n_a = np.array(a)
n_b = np.array([x for x in range(100, 106)])
n_c = np.concatenate([n_a, n_b])
np.sum(n_c) / len(n_c)

57.5

In [4]:
n_random = np.random.random(10)
n_random

array([0.54468115, 0.90751313, 0.38320304, 0.03302041, 0.08580039,
       0.68630696, 0.14215578, 0.71241732, 0.78656463, 0.15647562])

In [9]:
np.sort(n_random)[::-1]

array([0.90751313, 0.78656463, 0.71241732, 0.68630696, 0.54468115,
       0.38320304, 0.15647562, 0.14215578, 0.08580039, 0.03302041])